#include "Arduino.h"
#include "Consts.h"

Consts::Consts(){
	pinMode(MOTOR1_CLOCKWISE,OUTPUT);
	pinMode(MOTOR1_COUNTERCLOCKWISE,OUTPUT);
	pinMode(MOTOR2_CLOCKWISE,OUTPUT);
	pinMode(MOTOR2_COUNTERCLOCKWISE,OUTPUT);
	
	pinMode(MOTOR1_CHANNEL_A,INPUT);
	pinMode(MOTOR1_CHANNEL_B,INPUT);
	pinMode(MOTOR2_CHANNEL_A,INPUT);
	pinMode(MOTOR2_CHANNEL_B,INPUT);
	
	MOTOR_CHANNELS[0]=MOTOR1_CHANNEL_A;
	MOTOR_CHANNELS[1]=MOTOR1_CHANNEL_B;
	MOTOR_CHANNELS[2]=MOTOR2_CHANNEL_A;
	MOTOR_CHANNELS[3]=MOTOR2_CHANNEL_B;
}